# Build check workflow for development branch
# Runs on push to development branch to verify the app builds successfully
name: Build Check

on:
  # Runs on pushes to development branch
  push:
    branches: ["development", "dev"]
  
  # Runs on pull requests targeting development branch
  pull_request:
    branches: ["development", "dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job - only builds, doesn't deploy
  build-check:
    runs-on: ubuntu-latest
    name: Build Next.js App
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/front/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
          elif [ -f "${{ github.workspace }}/front/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
          else
            echo "Unable to determine package manager"
            exit 1
          fi
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: front/package-lock.json
          
      - name: Install dependencies
        run: |
          cd front
          ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
          
      - name: Build with Next.js
        run: |
          cd front
          ${{ steps.detect-package-manager.outputs.runner }} next build
          
      - name: Build Success ✅
        run: |
          echo "🎉 Next.js build completed successfully!"
          echo "✅ Ready for deployment"